name: Telegram notification

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Skeetry Web: ${{ github.actor }} - ${{ github.actor.url }} created a new pull request or or updated it [View all PR's](https://github.com/skeetry-app/web/pulls) | ${{ github.event.type }}) | ${{ github.repository }} | ${{github.sha}} | ${{ github.event.commits[0].message }}